#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime
version:      0.09
version_from: lib/DateTime.pm
installdirs:  site
requires:
    Test::More:                    0
    DateTime::TimeZone:            0.1
    Class::Factory::Util:          1.3
    Params::Validate:              0.52
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.06_05
