# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime
version:      0.22
version_from: lib/DateTime.pm
installdirs:  site
requires:
    Class::Factory::Util:          1.3
    DateTime::Locale:              0.09
    DateTime::TimeZone:            0.26
    Params::Validate:              0.72
    Pod::Man:                      1.14
    Test::More:                    0
    Time::Local:                   1.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
