--- #YAML:1.0
name:               DateTime
version:            0.47
abstract:           DateTime base objects
author:
    - Dave Rolsky <autarch@urth.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime::Locale:    0.41
    DateTime::TimeZone:  0.59
    Params::Validate:    0.76
    Pod::Man:            1.14
    Scalar::Util:        0
    Test::More:          0.34
    Time::Local:         1.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
