#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime
version:      0.1401
version_from: lib/DateTime.pm
installdirs:  site
requires:
    DateTime::Locale:              0.01
    DateTime::LeapSecond:          0.02
    Test::More:                    0
    DateTime::TimeZone:            0.25
    Class::Factory::Util:          1.3
    Params::Validate:              0.52
    Time::Local:                   1.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
