--- #YAML:1.0
name:                DateTime
version:             0.37
abstract:            DateTime base objects
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    DateTime::Locale:              0.34
    DateTime::TimeZone:            0.59
    Params::Validate:              0.76
    Pod::Man:                      1.14
    Scalar::Util:                  0
    Test::More:                    0.34
    Time::Local:                   1.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dave Rolsky <autarch@urth.org>
